version: '3.8'

services:
  vedic-web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NG_CLI_ANALYTICS=false
    stdin_open: true
    tty: true
    command: sh -c "NG_CLI_ANALYTICS=false npm start -- --host 0.0.0.0"
